language: node_js

node_js:
  - "6"
  - "5"
  - "7"
  - "stable"

sudo: false

before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start

script:
  - npm run lint
  - npm test
  - npm run build

notifications:
  email:
    on_failure: change

after_success:
  - npm run coveralls
